name: LeaftyBE

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/leaftybe .
          docker push ${{ secrets.DOCKER_USERNAME }}/leaftybe:latest

  continuous-deployment:
    needs: continuous-integration
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Stop and Remove Old Containers
        run: |
          docker stop leaftybe || true
          docker rm leaftybe || true

      - name: Remove Old Docker Image
        run: docker rmi ${{ secrets.DOCKER_USERNAME }}/leaftybe:latest || true

      - name: Pull Latest Backend Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/leaftybe:latest

      - name: Run New Containers
        run: |
          docker run -d \
            -p 5003:5003 \
            --name leaftybe \
            --restart always \
            -e EMAIL=${{secrets.EMAIL}} \
            -e PASSWORD=${{secrets.PASSWORD}} \
            -e XENDIT_API_KEY=${{secrets.XENDIT_API_KEY}} \
            -e INVOICE_API_KEY=${{secrets.INVOICE_API_KEY}} \
            -e BITESHIP_API_KEY=${{secrets.BITESHIP_API_KEY}} \
            leaftymp/leaftybe

      - name: Add Containers to Tunnel
        run: |
          docker network connect ${{ secrets.TUNNEL_NAME }} leaftymp/leaftybe || true